services:
  # Andrea Tombolato personal website
  personal-website:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/heyatomdev/website4:1.0.0
    container_name: personal-website
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    ports:
      - "3000:3000"
    networks:
      - internal_network

networks:
  internal_network:
